### ISSUE TITLE
individual name 'banner' still has links and dropdown triangle

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#14]
on mouseover the individual heading the mouse pointer changes to a pointing finger as if you are on a hyperlink but clicking does nothing.  Also the triangle icon on the header that normally expands and collapses additional info is still present although non functional.

**Comment by fisharebest** [comment]
> Also the triangle icon on the header that normally expands and collapses additional info is still present although non functional.

It expands/collapses the name details.  However, the details are hidden (via CSS), but this is still in progress because you weren't sure whether you wanted these details (i.e. given names, titles, nicknames, phonetic spellings, etc.) shown or not.

If you want them, I'll unhide them.  If you don't, I'll hide the rest of the things.  Let me know which...

**Comment by mtobiasjg** [comment]
I think we should show the nicknames etc…. so lets keep the triangles but enable them.

**Comment by fisharebest** [comment]
You can re-enable them by removing the appropriately commented section in the .CSS file.

**Comment by mtobiasjg** [comment]
i will keep disabled as in many/most cases they simply show the same name as already displayed.... alternate names display still.

is there no way to remove the triangles? and the mouseover change?

**Comment by fisharebest** [comment]
Removed.  Will send to you shortly.
