### ISSUE TITLE
Language menu

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/jg#16]
I included the language selector in the header, as I didn't know which languages your site supported.

Do you have multi-lingual support on your site?  Do you want it in this page?

At present, webtrees will auto-detect the language, so if an italian visits your site, they will see your header/footer in English, and the webtrees content in Italian.

1) do you want the language menu shown.
2) do you want webtrees to auto-detect the language
3) do you want webtrees to always use US-English

**Comment by mtobiasjg** [comment]
We DO want the language selector.

At the moment we have very little multi-lingual support.

I dont think we want auto-detect because many of our users access our website when travelling.  For example people visiting Poland might try and research while there but they dont speak Polish....

So yes please the selector but no auto-select. US-English is fine for the default.

HOWEVER looking to the future can you make this a configurable option in the theme?

**Comment by fisharebest** [comment]
Fixed.  I'll send you an update shortly.
